### ISSUE TITLE
Custom integration for Home Assistant

### ISSUE THREAD

**Issue by davidebeatrici** [cpttinkering/daren-485#1]
I found this project while searching for "DR-JC03", right after publishing a custom integration for Home Assistant: https://github.com/davidebeatrici/hass-dr-jc03

https://github.com/christian1980nrw/DR-JC03-RS485-Switcher was my only reference for the protocol itself, in fact I have only implemented the sensors that are provided in it.

Your README is impressive and appears to document most (if not all) of the protocol.

Would you be interested in contributing directly to my project?

**Comment by cpttinkering** [comment]
Hi David! 

Awesome to see you're putting this effort into integrating this BMS into homeassistant. 
While I do run Homeassistant, I'm not nearly skilled enough to write any meaningful code for that platform at the moment. Also, since I'm integrating the BMS in my Victron setup, which (along with a whole bunch of other info i need) is available trough Homeassistant trough MQTT allready. I personally don't have the need for this specific link just yet. 
Feel free to use any information or code of the dbus-serialbattery integration I wrote. 

Maybe some day!

Kind regards,

**Comment by davidebeatrici** [comment]
Hi, thank you very much for your reply!

I fully understand and respect your position. Feel free to take any improvements (e.g. async serial communication) from my project.

I'll probably integrate your protocol code and rename my project to `hass-daren-485`!

Best regards.
